version: '3.4'

services:
  dotnetkubernetes:
    image: ${DOCKER_REGISTRY}/dotnetkubernetes:${VERSION:-dev}
    build:
      context: .
      dockerfile: DotnetKubernetes/Dockerfile

  ngkubernetes:
    image: ${DOCKER_REGISTRY}/ngkubernetes:${VERSION:-dev}
    build:
      context: .
      dockerfile: AngularKubernetes/Dockerfile
